---
- name: upload or download an SSL Cert
  user: admin
  hosts: a10
  connection: local
  gather_facts: no
  vars:
    state: present
    partition: RCSIN_DEMO
  vars_prompt:
    - name: username
      prompt: username
      private: no
    - name: password
      prompt: password
      private: yes

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"

    - name: Upload an SSL key
      a10_ssl_v2: 
        host: "{{inventory_hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: no
        partition: "{{partition}}"
        state: "{{state}}"
        file_name: cert_app
        file_type: key
        method: upload
