- name: list a virtual server
  user: fadi
  hosts:  a10
  connection: local
  gather_facts: no
  vars:
    creds:
      part: "{{part}}"
      username: "{{username}}"
      password: "{{pass}}"

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a virtual server
      a10_read_virtual_server:
        validate_certs: no
        host: "{{inventory_hostname}}"
        username: ""
        password: ""
        creds: "{{creds}}"
#        partition: "{{creds}}"
#        virtual_server: vs_server0
#        virtual_server_ip: 1.1.1.1
