---
- name: create a realserver
  user: admin
  hosts: a10
  connection: local
  gather_facts: no
  vars:
    state: present
    partition: RCSIN_DEMO
  vars_prompt:
    - name: username
      prompt: username
      private: no
    - name: password
      prompt: password
      private: yes


  tasks:
    - debug:
        msg: "{{inventory_hostname}}"

    - name: Create a realserver
      a10_server_v2:
        host: "{{inventory_hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        state: present
        validate_certs: no
        partition: "{{partition}}"
        server_name: "rip_server_v6_1"
        server_ip: "fe80::100"
        server_ports:
            - port_num: 80
              protocol: tcp
              health_monitor: "no"
            - port_num: 8443
              protocol: tcp

    - name: Create another realserver
      a10_server_v2:
        host: "{{inventory_hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: no
        partition: "{{partition}}"
        server_name: "rip_server_v6_2"
        server_ip: "fe80::101"
        server_ports:
            - port_num: 8080
              protocol: tcp
            - port_num: 443
              protocol: tcp
