- name: create a virtual server
  user: fadi
  hosts:  a10
  connection: local
  gather_facts: no
  vars:
    state: present
    partition: RCSIN_PRV
  vars_prompt:
    - name: username
      prompt: username
      private: no
    - name: password
      prompt: password
      private: yes

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"
    - name: Create a virtual server
      a10_virtual_server_v2:
        validate_certs: no
        host: "{{inventory_hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        partition: "{{partition}}"
        virtual_server: vs_server1
        virtual_server_ip: 1.1.1.1
        redistribution_flagged: True
        disable_vserver_on_condition: 0
        virtual_server_ports:
          - port: 80
            protocol: TCP
            service_group: sg-80-tcp
            tcp_template: ""
            extended_stats: ""
            ssl_session_id_persistence_template: "sslidtemplate"
            source_nat: ""
            ha_connection_mirror: 1
          - port: 443
            protocol: HTTPS
            tcp_proxy_template: ""
            aflex_list: ['abc','def']
            service_group: sg-80-tcp
            client_ssl_template: ""
            http_template: ""
          - port: 8080
            protocol: http
            service_group: sg-80-tcp
            http_template: ""
            cookie_persistence_template: ""
            acl_natpool_binding_list: [{acl_id: 102, nat_pool: "testingpool"}] 
